spring:
  datasource:
    password: itcast
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.201.137:3306/master_music?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10